[package]
name = "rustlanti"
version = "0.1.0"
authors = ["oktaysabak <oktaysabak@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.6"

[[bin]]
name = "rustlanti"
path = "main.rs"
